services:
  bind:
    build: ./bind
    container_name: lucos_dns_secondary_bind
    ports:
      - "53:53"
      - "53:53/udp"
    image: lucas42/lucos_dns_secondary_bind:${VERSION:-latest}
    restart: always
    environment:
      - TSIG_SECRET
    volumes:
      - "secondaryzones:/etc/bind/secondary-zones"
    healthcheck:
      test: ["CMD-SHELL", "dig @127.0.0.1 localhost +short > /dev/null"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  check:
    build: ./check
    container_name: lucos_dns_secondary_check
    image: lucas42/lucos_dns_secondary_check:${VERSION:-latest}
    restart: always
    environment:
      - SCHEDULE_TRACKER_ENDPOINT
    depends_on:
      - bind
    healthcheck:
      test: ["CMD-SHELL", "ps | grep -q '[s]upercronic'"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  secondaryzones:

networks:
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:3::/64
